### ISSUE TITLE
Make it multilingual

### ISSUE THREAD

**Issue by ensag-dev** [vemonet/EmojiMart#3]
Thanks for your app!
Would it be possible to make it handle other languages than English?

**Comment by vemonet** [comment]
Hi @ensag-dev , yes it should be doable as the emoji-mart web component already support internationalization: https://github.com/missive/emoji-mart#-internationalization 

All those languages are supported: https://github.com/missive/emoji-mart/tree/main/packages/emoji-mart-data/i18n 

But it seems to be only for the UI elements, I am not sure if it includes also internationalization of the emojis keywords

Currently I don't really have a system to enable configuration through the UI (I would like to keep it as minimal as possible at the moment), but this could be done using the command line

e.g. with flatpak: `flatpak run io.github.vemonet.EmojiMart --lang fr`

Would that work for you?

If we notice that internationalization is not supported for emojis keyword we can check to improve the emoji-mart web component directly

**Comment by vemonet** [comment]
Complete translation is done using this script: https://github.com/vemonet/EmojiMart/blob/main/resources/internationalize.js checkout the readme for detail on how to use localization
