### ISSUE TITLE
🐞 The readme Flatpak link is not working

### ISSUE THREAD

**Issue by supng** [vemonet/EmojiMart#5]
### Describe the bug

The readme states to run 

`curl -Lo io.github.vemonet.EmojiMart.flatpak https://github.com/vemonet/EmojiMart/releases/latest/download/io.github.vemonet.EmojiMart.flatpak`

But releases does not have any .flatpak file.

### Operating System

Nobara 38

### Emoji Mart version

Latest

**Comment by vemonet** [comment]
Indeed the modified flatpak was not uploaded properly, I have removed instructions for autopaste on wayland for now, will see in the future when XDG portals and cie will finally be usable (after 15 years of wayland we still don't have the basic APIs required to interact with the desktop 😅)
