### ISSUE TITLE
🐞 link to flatpak release is broken 

### ISSUE THREAD

**Issue by KhaaL** [vemonet/EmojiMart#7]
### Describe the bug

There is an error in the instructions for autopaste, the command `curl -Lo io.github.vemonet.EmojiMart.flatpak https://github.com/vemonet/EmojiMart/releases/latest/download/io.github.vemonet.EmojiMart.flatpak` points to a URL that is non-existant (https://github.com/vemonet/EmojiMart/releases/download/v0.2.4/io.github.vemonet.EmojiMart.flatpak). There are no flatpaks in the releases that allows for a manual installation either.

### Operating System

OS-agnostic

### Emoji Mart version

latest

**Comment by vemonet** [comment]
Indeed the modified flatpak was not uploaded properly, I have removed instructions for autopaste on wayland for now, will see in the future when XDG portals and cie will finally be usable (after 15 years of wayland we still don't have the basic APIs required to interact with the desktop 😅)
